Resources:
  PortfolioOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: portfolio-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  PortfolioDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Portfolio static site'
        DefaultRootObject: index.html
        Origins:
          - Id: s3-origin
            DomainName: !GetAtt PortfolioBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt PortfolioOAC.Id
        DefaultCacheBehavior:
          TargetOriginId: s3-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
        Aliases:
          - ${self:custom.domainName}
          - !Sub 'www.${self:custom.domainName}'
        ViewerCertificate:
          AcmCertificateArn: !Ref PortfolioCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

Outputs:
  PortfolioDistributionId:
    Value: !Ref PortfolioDistribution
    Export:
      Name: PortfolioDistributionId
  PortfolioDistributionDomainName:
    Value: !GetAtt PortfolioDistribution.DomainName
    Export:
      Name: PortfolioDistributionDomainName
  PortfolioDistributionHostedZoneId:
    Value: Z2FDTNDATAQYW2
    Export:
      Name: PortfolioDistributionHostedZoneId
